name : python workflow

on :

  workflow_dispatch:

jobs : 
  python-job :
    runs-on : ubuntu-latest
    environment :
      name : production
    steps :
     - name : install dependencies
       id : step_one
       run : | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
     - name : run tests
       id : step_Two
       run : pytest test_TestApp.py